[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm turbo build --filter=@bookzi/api"]

[start]
cmd = "node apps/api/dist/server.js"
